/* TM LINK 공통 스크립트: 앱 소개 데이터 · 다국어 · 언어 전환 (홈 / 비즈홈 / 앱 소개 페이지가 함께 씀) */
var APPS = {
 mandu:{ url:'https://jinjjabg-hub.github.io/MANDU/', icon:'#i-chat', latin:'MANDU',
  ko:{cat:'통번역 메신저',name:'만두',lead:'언어가 달라도 대화는 하나로. 상대가 외국어로 써도 내 언어로 읽고, 내 언어로 쓰면 상대 언어로 전달됩니다.',
      when:['해외 바이어·외국인 고객과 상담할 때','외국인 직원·거래처와 매일 연락할 때','해외 출장·여행 중 현지인과 대화할 때'],
      feat:['14개 언어 실시간 자동 번역 채팅','사진·파일 전송, 친구·채팅방','비즈니스 프로필 링크로 나를 소개','구글·이메일로 바로 시작'],
      price:'무료로 시작 · 필요하면 플랜 업그레이드',open:'만두 열기'},
  en:{cat:'Translation messenger',name:'MANDU',lead:'Different languages, one conversation. Read their messages in your language, and they read yours in theirs.',
      when:['Talking with overseas buyers or foreign clients','Daily contact with foreign staff or partners','Chatting with locals on business trips or travel'],
      feat:['Real-time translated chat in 14 languages','Photos, files, friends and group chats','Share a business profile link','Start instantly with Google or email'],
      price:'Free to start · upgrade plans available',open:'Open MANDU'},
  zh:{cat:'翻译聊天',name:'MANDU',lead:'语言不同，对话如一。对方用外语写，您用母语读；您用母语写，对方用他的语言读。',
      when:['与海外买家·外国客户沟通时','与外籍员工·合作伙伴日常联系时','出差·旅行时与当地人交流时'],
      feat:['14 种语言实时自动翻译聊天','发送照片·文件，好友·群聊','用商务名片链接介绍自己','用 Google·邮箱即可开始'],
      price:'免费开始 · 可升级方案',open:'打开 MANDU'},
  ja:{cat:'翻訳メッセンジャー',name:'MANDU',lead:'言葉が違っても会話は一つに。相手の外国語は自分の言語で読め、自分の言葉は相手の言語で届きます。',
      when:['海外バイヤー・外国人顧客と相談する時','外国人スタッフ・取引先と毎日連絡する時','出張・旅行先で現地の人と話す時'],
      feat:['14 言語のリアルタイム自動翻訳チャット','写真・ファイル送信、友だち・グループ','ビジネスプロフィールのリンクで自己紹介','Google・メールですぐ開始'],
      price:'無料で開始 · 必要に応じてプランをアップグレード',open:'MANDU を開く'}},
 jujudosa:{ url:'https://jinjjabg-hub.github.io/JUJUDOSA/', icon:'#i-star', latin:'JUJUDOSA',
  ko:{cat:'AI 사주 상담',name:'주주도사',lead:'타고난 명식을 읽고, 지금 시기에 맞는 조언을 건네는 사주 상담. 궁금한 건 도사님께 채팅으로 물어보세요.',
      when:['이직·창업 시기가 고민될 때','인연·결혼 운이 궁금할 때','재물 흐름을 미리 보고 싶을 때'],
      feat:['종합 사주 풀이 — 인생의 큰 흐름','전문 도사님께 AI 채팅으로 질문','궁합 보기 (결혼 시기·경제적 조화)','귀인지도 — 친구 불러 관계 지도 (무료)'],
      price:'무료 (주간 운세·AI 채팅 3회) · 라이트 월 4,900원 · 스탠다드 월 9,900원 (VAT 포함)',open:'주주도사 열기'},
  en:{cat:'AI saju counseling',name:'JUJUDOSA',lead:'Korean saju counseling that reads your birth chart and gives advice for this season of life. Ask the masters anything by chat.',
      when:['Deciding when to change jobs or start a business','Curious about relationships or marriage','Wanting a look at your wealth flow'],
      feat:['Full saju reading — your life’s big picture','Ask expert masters via AI chat','Compatibility (marriage timing, finances)','Gwiin Map — invite friends to map relationships (free)'],
      price:'Free (weekly fortune, 3 AI chats) · Lite ₩4,900/mo · Standard ₩9,900/mo (VAT incl.)',open:'Open JUJUDOSA'},
  zh:{cat:'AI 四柱咨询',name:'JUJUDOSA',lead:'解读您的先天命盘，给出适合当下时期的建议。有疑问可以用聊天直接问道士。',
      when:['纠结跳槽·创业时机时','想了解姻缘·婚姻运时','想提前看看财运走势时'],
      feat:['综合四柱解读——人生大方向','通过 AI 聊天向专业道士提问','合婚（结婚时机·经济协调）','贵人地图——邀请朋友绘制关系图（免费）'],
      price:'免费（每周运势·AI 聊天 3 次）· 轻享 月 4,900韩元 · 标准 月 9,900韩元（含增值税）',open:'打开 JUJUDOSA'},
  ja:{cat:'AI 四柱推命相談',name:'JUJUDOSA',lead:'生まれ持った命式を読み、今の時期に合ったアドバイスを届ける四柱推命相談。気になることは導師にチャットで聞けます。',
      when:['転職・起業のタイミングに迷う時','縁・結婚運が気になる時','金運の流れを先に知りたい時'],
      feat:['総合四柱推命 — 人生の大きな流れ','専門の導師に AI チャットで質問','相性診断（結婚時期・経済的な相性）','貴人マップ — 友だちを招いて関係図（無料）'],
      price:'無料（週間運勢・AI チャット 3 回）· ライト 月 4,900ウォン · スタンダード 月 9,900ウォン（VAT 込）',open:'JUJUDOSA を開く'}},
 cardbook:{ url:'https://jinjjabg-hub.github.io/cardbook/', icon:'#i-book', latin:'CardBook',
  ko:{cat:'명함 관리',name:'카드북',lead:'받은 명함을 한곳에 모으고, 기억나는 조각만으로 바로 찾는 명함첩.',
      when:['모임에서 받은 명함이 쌓여 있을 때','"그 세무사님 누구였지?" 이름이 기억 안 날 때','디지털 명함을 받고 저장할 곳이 필요할 때'],
      feat:['명함 이미지에서 정보 자동 추출 (여러 장 한 번에)','카톡·이메일로 받은 명함 이미지 인식','휴대폰 연락처 불러오기 (안드로이드 크롬)','디지털 명함의 \'명함첩에 저장\' 버튼과 연동'],
      price:'무료',open:'카드북 열기'},
  en:{cat:'Card manager',name:'CardBook',lead:'Keep every card you receive in one place and find people by whatever you remember.',
      when:['Cards from meetups are piling up','You can’t recall a name — “who was that accountant?”','You need a place to save digital cards'],
      feat:['Auto-extract info from card images (many at once)','Reads card images received via KakaoTalk or email','Import phone contacts (Android Chrome)','Works with the “Save to CardBook” button on digital cards'],
      price:'Free',open:'Open CardBook'},
  zh:{cat:'名片管理',name:'名片册',lead:'把收到的名片集中保存，凭记忆片段即可快速找到。',
      when:['聚会收到的名片越积越多时','想不起名字——"那位税务师是谁？"','收到数字名片需要保存时'],
      feat:['从名片图片自动提取信息（可一次多张）','识别 KakaoTalk·邮件收到的名片图片','导入手机通讯录（安卓 Chrome）','与数字名片的"存入名片册"按钮联动'],
      price:'免费',open:'打开名片册'},
  ja:{cat:'名刺管理',name:'カードブック',lead:'受け取った名刺を一か所に集め、覚えている断片だけですぐ探せる名刺帳。',
      when:['集まりでもらった名刺がたまっている時','「あの税理士さん誰だっけ？」と名前が出てこない時','デジタル名刺の保存先が必要な時'],
      feat:['名刺画像から情報を自動抽出（複数枚まとめて）','カカオトーク・メールで届いた名刺画像も認識','スマホの連絡先を読み込み（Android Chrome）','デジタル名刺の「名刺帳に保存」ボタンと連携'],
      price:'無料',open:'カードブックを開く'}},
 autocard:{ url:'https://jinjjabg-hub.github.io/autocard/', icon:'#i-bolt', latin:'AutoCard',
  ko:{cat:'디지털 명함',name:'오토명함',lead:'명함 사진 한 장, 5분이면 완성되는 디지털 명함. 받은 사람은 카드북에 바로 저장합니다.',
      when:['지금 당장 디지털 명함이 필요할 때','부담 없는 비용으로 먼저 시작하고 싶을 때','직원·팀원 명함을 빠르게 만들 때'],
      feat:['명함 사진 한 장으로 AI가 초안 작성','템플릿 6종 중 골라 바로 발행','링크로 공유, 받은 사람은 카드북에 저장','미리보기 그대로 공개 명함 발행'],
      price:'5,900원부터',open:'오토명함 만들기'},
  en:{cat:'Digital card',name:'AutoCard',lead:'A digital card done in 5 minutes from one photo. Recipients save it straight to CardBook.',
      when:['You need a digital card right now','You want to start at a low cost','Making cards quickly for staff or a team'],
      feat:['AI drafts it from one card photo','Pick from 6 templates and publish','Share by link; recipients save to CardBook','Publish exactly what you preview'],
      price:'From ₩5,900',open:'Make an AutoCard'},
  zh:{cat:'数字名片',name:'自动名片',lead:'一张名片照片，5 分钟完成的数字名片。对方可直接存入名片册。',
      when:['马上需要数字名片时','想以低成本先开始时','需要快速为员工·团队制作名片时'],
      feat:['一张名片照片，AI 自动生成初稿','6 种模板任选，即刻发布','通过链接分享，对方存入名片册','所见即所得发布'],
      price:'5,900韩元起',open:'制作自动名片'},
  ja:{cat:'デジタル名刺',name:'オート名刺',lead:'名刺写真 1 枚、5 分で完成するデジタル名刺。受け取った人はカードブックにすぐ保存。',
      when:['今すぐデジタル名刺が必要な時','負担の少ない費用でまず始めたい時','スタッフ・チームの名刺を素早く作る時'],
      feat:['名刺写真 1 枚から AI が下書き','6 種のテンプレートから選んですぐ発行','リンクで共有、相手はカードブックに保存','プレビューそのままの名刺を公開'],
      price:'5,900ウォンから',open:'オート名刺を作る'}}
};
var SHEET_UI = {
 ko:{when:'이럴 때 좋아요',feat:'주요 기능',price:'가격',install:'홈 화면에 설치하기',close:'닫기',
     note:'앱스토어 없이 바로 쓰는 웹앱이에요. 홈 화면에 추가하면 앱처럼 열립니다.',
     ios:['Safari로 앱을 엽니다','아래쪽 공유 버튼(□↑)을 누릅니다','"홈 화면에 추가"를 누릅니다'],
     and:['Chrome으로 앱을 엽니다','오른쪽 위 ⋮ 메뉴를 누릅니다','"앱 설치" 또는 "홈 화면에 추가"를 누릅니다']},
 en:{when:'Great for',feat:'Key features',price:'Price',install:'Add to home screen',close:'Close',
     note:'A web app — no app store needed. Add it to your home screen and it opens like an app.',
     ios:['Open the app in Safari','Tap the Share button (□↑) at the bottom','Tap “Add to Home Screen”'],
     and:['Open the app in Chrome','Tap the ⋮ menu at the top right','Tap “Install app” or “Add to Home screen”']},
 zh:{when:'适用场景',feat:'主要功能',price:'价格',install:'添加到主屏幕',close:'关闭',
     note:'无需应用商店的网页应用。添加到主屏幕后即可像应用一样打开。',
     ios:['用 Safari 打开应用','点击底部的分享按钮（□↑）','点击"添加到主屏幕"'],
     and:['用 Chrome 打开应用','点击右上角的 ⋮ 菜单','点击"安装应用"或"添加到主屏幕"']},
 ja:{when:'こんな時に',feat:'主な機能',price:'料金',install:'ホーム画面に追加',close:'閉じる',
     note:'アプリストア不要のウェブアプリです。ホーム画面に追加するとアプリのように開きます。',
     ios:['Safari でアプリを開く','下の共有ボタン（□↑）をタップ','「ホーム画面に追加」をタップ'],
     and:['Chrome でアプリを開く','右上の ⋮ メニューをタップ','「アプリをインストール」または「ホーム画面に追加」をタップ']}
};
var curLang = 'ko', curApp = null;

// ===== 다국어 (한국어는 HTML 원문을 그대로 사용) =====
var I18N = {
en:{
 u1v:'Free',
 n5:'Custom domain: ask separately',
 beta:'Pilot',
 p2_6:'🌏 Up to 6 languages + customer reviews',
 p2_5:'🛠 1 year of image & design updates (2 image swaps + 1 redesign · worth ₩115k)',
 p2_4:'📊 Monthly visit report — who viewed and what they tapped',
 p2_3:'📩 Inquiry form + instant alerts — your BizHome sells for you',
 p2_2:'📣 My News Board — post products, cases and news from your phone',
 p2_1:'🎬 Hero AI video — a first screen that moves',
 p2_0:'Everything in Standard +',
 p1_12:'Ready in about 3 days',
 p1_11:'Free hosting (₩0 upkeep)',
 p1_10:'Photo & design changes handled by TM LINK',
 p1_9:'✏️ Edit your text anytime — no waiting on requests, one edit button; EN·JP·CN auto-translated',
 p1_8:'Visit & click stats (“Card stats”)',
 p1_7:'Save contact · Share · Save to CardBook · MANDU · QR',
 p1_6:'4 languages (KR·EN·JP·CN)',
 p1_5:'Portfolio (when your field needs it)',
 p1_4:'“Please introduce me to…” referral section',
 p1_3:'Intro · Why · Difference · Career · Services sections',
 p1_2:'2 AI images — hero image + profile photo',
 p1_1:'1:1 custom design (no templates)',
 hint:'Scroll it yourself with your mouse',
 sc3_p:'Planning, design, development and upkeep. Too much time and cost just to introduce one leader.',
 sc3_h:'A company website',
 sc3_w:'Too heavy',
 sc2_p:'Intro, career, services and referrals on one page. Shared by one link, ready in about 3 days.',
 sc2_h:'BizHome',
 sc2_w:'Just right',
 sc1_p:'Name and contact. Hard to show what you do best or why it should be you.',
 sc1_h:'A business card',
 sc1_w:'Too light',
 live:'Live BizHome sample · Seunghoon Song',
 cmp_src:'※ Market data: <a href="https://kmong.com/best-gig/47--%EB%88%84%EA%B5%AC%EB%82%98-%EC%89%BD%EA%B2%8C-%EA%B0%9C%EC%9D%B8-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%A0%9C%EC%9E%91%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95" target="_blank" rel="noopener">Kmong “Personal website”</a> quotes (min ₩400k · max ₩1.8M · avg ₩800k, checked Oct 2026). Varies by features and pages.',
 fh1:'1:1 planning & design',fh2:'4 languages included',fh3:'₩0 upkeep',fh4:'Ready in ~3 days',
 r6c:'KakaoTalk preview · QR included',
 r6a:'Mobile & KakaoTalk optimization extra',
 r6:'Sharing',
 c_web:'Typical freelance personal website',
 cat5:'AI fortune',
 cat4:'Translation messenger',
 cat3:'Card manager',
 cat2:'Digital card',
 cat1:'Personal brand website',
 nav_apps:'Apps',nav_why:'BizHome',nav_price:'Pricing',nav_process:'Process',nav_cta:'Apply',
 hero_tag:'Between a card and a website · BizHome',
 hero_h:'A card isn’t enough,<br/>a website feels too much.<br/><span class="hl">BizHome.</span>',
 hero_sub:'The story a single card can’t hold, without the weight of a full website. <b>BizHome</b> puts your intro, career, services and referrals on one personal brand page. Hand over one link — they truly get to know you.',
 hero_btn1:'See BizHome pricing',hero_btn2:'See our work',
 st1:'Monthly<br/>hosting cost',st2:'Languages<br/>included',st3:'Build time<br/>(Standard)',st4:'Business day<br/>to reply',
 apps_h:'Services by TM LINK',apps_sub:'BizHome, our flagship service, plus apps you can use separately. All built and run by TM LINK.',
 app_badge:'Flagship',app1_n:'BizHome',app1_d:'Deeper than a card, lighter than a website. A personal brand page planned and designed one-on-one for you.',app1_t:'₩150k · ₩250k →',
 app2_n:'AutoCard',app2_d:'A digital card done in 5 minutes from one photo. Pick from 6 templates and publish.',app2_t:'From ₩5,900 →',
 app3_n:'CardBook',app3_d:'Keep every card you receive in one place and find people by whatever you remember.',app3_t:'Try free →',
 app4_n:'MANDU',app4_d:'Different languages, one conversation. A messenger with real-time translation in 14 languages.',app4_t:'Try messenger →',
 app5_n:'JUJUDOSA',app5_d:'AI saju (Korean fortune) counseling: daily fortune, compatibility and timely advice.',app5_t:'Start →',
 why_h:'Deeper than a card,<br/>lighter than a website.',
 why_sub:'As easy to hand over as a card, as complete as a website. Exactly what a referred client needs when they look you up.',
 b1_h:'One-on-one, not a template',b1_p:'Designed personally after hearing your industry, style and customers. No two BizHomes are alike.',
 b2_h:'One link says it all',b2_p:'Optimized KakaoTalk preview with your photo and intro. A QR code is included.',
 b3_h:'"Please introduce me to…"',b3_p:'A partner & referral section built on the BNI model, so people know exactly whom to connect you with.',
 b4_h:'4 languages built in',b4_p:'Korean, English, Chinese and Japanese switch by default — ready for overseas buyers.',
 b5_h:'₩0 upkeep',b5_p:'Runs with no server or hosting fees. No monthly maintenance bills after launch.',
 b6_h:'Edit text anytime',b6_p:'Phone, title or intro — no waiting on requests, one edit button changes it instantly. EN·JP·CN auto-translated; photos and design handled by TM LINK.',
 cmp_h:'What would it cost as a website?',cmp_sub:'Compared with ordering the same content as a personal website on a freelance marketplace.',
 c_biz:'BizHome',
 
 r2:'Price',r2a:'<b class="mkt">Avg. ₩800k</b><span class="range">₩400k – ₩1.8M</span>',r2c:'<b class="our">₩150k · ₩250k</b><span class="range">Fixed price · scope published per plan</span>',
 r3:'Process',r3a:'Planning → design → development in stages',r3c:'1:1 consultation, ready in about 3 days',
 r4:'Upkeep',r4a:'Hosting, domain and maintenance extra',r4c:'₩0 hosting',
 r5:'Languages',r5a:'Extra work per language',r5c:'4 languages included',
 pr_h:'Custom BizHome — just pick one of two.',pr_sub:'Both are made one-on-one without templates. The difference: stop at introducing, or go on to selling.',
 p1_d:'A BizHome that properly introduces you and your work',
 p1_btn:'Apply for Standard',
 p2_best:'Beyond intro — into sales',p2_d:'Shows, announces, and brings in inquiries',
 p2_btn:'Apply for Premium',
 n1:'VAT (10%) not included',n2:'Production starts after payment',n4:'10+ cards for teams: custom quote',
 g_h:'See real BizHomes we have made',g_p:'Opens the gallery of finished work by industry',g_btn:'View gallery',
 ps_h:'4 steps from application to launch',ps_sub:'The form takes 1 minute. We fill in the rest together.',
 s1_h:'Apply',s1_p:'Choose a plan and leave basic info. We reply within 1 business day.',
 s2_h:'Consult · send materials',s2_p:'We learn what you do, whom you serve and who you want to meet, then collect photos and logos.',
 s3_h:'Design · revise',s3_p:'You get a custom draft and we refine it within your plan’s revisions.',
 s4_h:'Launch · QR',s4_p:'You receive your website address and QR. Introduce yourself with one address from today.',
 ac_h:'Don’t rebuild. Update for less.',ac_sub:'Update prices for BizHome customers.',
 u1:'Text edits',u1d:'Edit button, instantly (once a month)',u2:'Photo/image swap',u2d:'Profile, cover, etc.',u3:'Design renewal',u3v:'50% off',u3d:'Structure & layout',u4:'Full rebuild',u4v:'30% off',u4d:'New industry or brand',
 rf1:'Before production',rf1v:'100% refund',rf2:'Before 1st revision',rf2v:'50% refund',rf3:'After 1st revision',rf3v:'No refund',
 mk_q:'"I help each leader become <em>a brand of their own</em>."',
 mk_p:'Exchanging referrals at BNI, I often saw introductions stall when someone asked, "So what exactly does this person do?" and there was nothing to show. BizHome is the website that answers that question.',
 mk_who:'Seunghoon Song · CEO, T.M Link · BNI Pioneer (Busan)',
 f_h:'Make your next introduction your website address.',f_p:'Busan · remote nationwide · reply within 1 business day',f_btn1:'Apply for BizHome',f_btn2:'See our work',
 ft_by:'Seunghoon Song · T.M Link · BNI Pioneer'
},
zh:{
 u1v:'免费',
 n5:'个人域名绑定请另行咨询',
 beta:'试运营',
 p2_6:'🌏 最多 6 种语言 + 客户评价板块',
 p2_5:'🛠 1 年图片·设计修改（更换图片 2 次 + 设计翻新 1 次 · 价值 11.5 万韩元）',
 p2_4:'📊 月度访问报告——多少人看过、点了什么',
 p2_3:'📩 咨询表单 + 即时通知——让 BizHome 成为营销工具',
 p2_2:'📣 我的动态板——用手机随时发布产品·案例·动态',
 p2_1:'🎬 主视觉 AI 视频——一打开就会动的首屏',
 p2_0:'包含标准版全部内容 +',
 p1_12:'制作周期约 3 天',
 p1_11:'免费托管（零维护费）',
 p1_10:'照片·设计变更由 TM LINK 负责',
 p1_9:'✏️ 随时修改文字——无需提出请求等待，一个按钮即可修改，英·日·中自动翻译',
 p1_8:'访问·点击统计（"名片概况"）',
 p1_7:'保存联系人·分享·存入名片册·MANDU·二维码',
 p1_6:'4 种语言（韩·英·日·中）',
 p1_5:'作品集（行业需要时）',
 p1_4:'"请帮我介绍这样的人"引荐板块',
 p1_3:'介绍·Why·差异·经历·服务板块',
 p1_2:'AI 图片 2 张——主视觉图 + 头像',
 p1_1:'一对一定制设计（无模板）',
 hint:'用鼠标滚轮自己浏览',
 sc3_p:'策划、设计、开发、维护。只为介绍一位代表，时间和成本都太高。',
 sc3_h:'公司官网',
 sc3_w:'太重',
 sc2_p:'介绍·经历·服务·引荐尽在一页。一个链接即可分享，约 3 天完成。',
 sc2_h:'BizHome',
 sc2_w:'刚刚好',
 sc1_p:'只有姓名和联系方式，难以说明您擅长什么、为什么选您。',
 sc1_h:'一张名片',
 sc1_w:'太轻',
 live:'真实 BizHome 案例 · 宋承勋',
 cmp_src:'※ 行情来源：<a href="https://kmong.com/best-gig/47--%EB%88%84%EA%B5%AC%EB%82%98-%EC%89%BD%EA%B2%8C-%EA%B0%9C%EC%9D%B8-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%A0%9C%EC%9E%91%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95" target="_blank" rel="noopener">Kmong「个人网站制作」</a>报价数据（最低 40万 · 最高 180万 · 平均 80万韩元，2026年10月查询）。因功能和页数而异。',
 fh1:'一对一策划·设计',fh2:'默认 4 种语言',fh3:'零维护费',fh4:'约 3 天完成',
 r6c:'默认提供 KakaoTalk 预览 · 二维码',
 r6a:'移动端·KakaoTalk 优化另计',
 r6:'分享',
 c_web:'一般外包个人网站',
 cat5:'AI 四柱',
 cat4:'翻译聊天',
 cat3:'名片管理',
 cat2:'数字名片',
 cat1:'个人品牌官网',
 nav_apps:'应用',nav_why:'BizHome',nav_price:'价格',nav_process:'流程',nav_cta:'申请',
 hero_tag:'名片与官网之间 · BizHome',
 hero_h:'名片不够用，<br/>官网又太重。<br/><span class="hl">BizHome。</span>',
 hero_sub:'一张名片装不下的故事，不必做成沉重的官网。<b>BizHome</b> 把您的介绍、经历、服务和引荐放在一页个人品牌主页上。递出一个链接，对方就能真正了解您。',
 hero_btn1:'查看 BizHome 价格',hero_btn2:'查看案例',
 st1:'每月<br/>托管费用',st2:'默认<br/>支持语言',st3:'制作周期<br/>（标准版）',st4:'申请后<br/>工作日内回复',
 apps_h:'TM LINK 的服务',apps_sub:'核心服务 BizHome，以及可单独使用的应用。全部由 TM LINK 自主开发运营。',
 app_badge:'核心服务',app1_n:'BizHome',app1_d:'比名片更深入，比官网更轻巧的个人品牌主页。为您一对一策划设计。',app1_t:'15万 · 25万韩元 →',
 app2_n:'自动名片',app2_d:'一张名片照片，5 分钟完成的数字名片。6 种模板任选，即刻发布。',app2_t:'5,900韩元起 →',
 app3_n:'名片册',app3_d:'把收到的名片集中保存，凭记忆片段即可快速找到。',app3_t:'免费使用 →',
 app4_n:'MANDU',app4_d:'语言不同，对话如一。支持 14 种语言实时翻译的聊天应用。',app4_t:'体验 →',
 app5_n:'JUJUDOSA',app5_d:'AI 四柱咨询：解读命盘，给出当下的建议。今日运势、合婚尽在其中。',app5_t:'开始咨询 →',
 why_h:'比名片更深入，<br/>比官网更轻巧。',
 why_sub:'像名片一样容易递出，像官网一样内容充足。正好满足被引荐者搜索您时所需。',
 b1_h:'一对一定制，而非模板',b1_p:'了解您的行业、风格和客户后亲自设计。没有两个相同的 BizHome。',
 b2_h:'一个链接完成介绍',b2_p:'优化 KakaoTalk 预览，照片与简介即刻显示，并附赠二维码。',
 b3_h:'"请帮我介绍这样的人"',b3_p:'按 BNI 引荐模式设计的伙伴·推荐板块，对方立刻知道该为您连接谁。',
 b4_h:'内置 4 种语言',b4_p:'韩、英、中、日一键切换，可直接发给海外买家和外国客户。',
 b5_h:'零维护费',b5_p:'无需服务器和托管费用即可持续运营，上线后没有每月管理费。',
 b6_h:'文字随时修改',b6_p:'电话、职务、介绍——无需提出请求等待，一个按钮即刻修改。英·日·中自动翻译，照片·设计由 TM LINK 负责。',
 cmp_h:'如果做成官网要多少钱？',cmp_sub:'与在外包平台把同样内容做成个人网站的情况比较。',
 c_biz:'BizHome',
 
 r2:'价格',r2a:'<b class="mkt">平均 80万韩元</b><span class="range">40万 ~ 180万韩元</span>',r2c:'<b class="our">15万 · 25万韩元</b><span class="range">明码标价 · 各方案内容公开</span>',
 r3:'进行方式',r3a:'策划 → 设计 → 开发 分阶段进行',r3c:'一对一咨询后约 3 天完成',
 r4:'维护费',r4a:'托管·域名·管理费另计',r4c:'托管 0 元',
 r5:'多语言',r5a:'每种语言需额外制作',r5c:'默认包含 4 种语言',
 pr_h:'BizHome 定制，二选一即可。',pr_sub:'两者都无模板、一对一制作。区别在于：停在介绍，还是延伸到营销。',
 p1_d:'好好介绍您和您事业的 BizHome',
 p1_btn:'申请标准版',
 p2_best:'从介绍到营销',p2_d:'展示、发布，还能接收咨询的 BizHome',
 p2_btn:'申请高级版',
 n1:'不含增值税（10%）',n2:'确认付款后开始制作',n4:'10 张以上团体·企业另行报价',
 g_h:'查看实际制作的 BizHome',g_p:'前往按行业分类的作品展示',g_btn:'查看作品',
 ps_h:'从申请到完成 4 步',ps_sub:'申请表 1 分钟完成，其余边沟通边完善。',
 s1_h:'填写申请',s1_p:'选择方案并留下基本信息即可。1 个工作日内联系您。',
 s2_h:'咨询 · 提交资料',s2_p:'了解您的业务、目标客户与想认识的人，并收集照片和标志。',
 s3_h:'设计 · 修改',s3_p:'发送定制初稿，在方案修改次数内细化。',
 s4_h:'发布 · 二维码',s4_p:'交付网址和二维码。从今天起用一个网址介绍自己。',
 ac_h:'不必重做，低价更新。',ac_sub:'BizHome 客户专享更新价格。',
 u1:'文字修改',u1d:'用修改按钮即时更新（每月 1 次）',u2:'照片·图片更换',u2d:'头像、封面等',u3:'设计翻新',u3v:'5 折',u3d:'结构·版式变更',u4:'整体重做',u4v:'7 折',u4d:'行业·品牌转换',
 rf1:'开始制作前',rf1v:'全额退款',rf2:'第一次修改前',rf2v:'退款 50%',rf3:'第一次修改后',rf3v:'不予退款',
 mk_q:'"让每位代表都成为<em>一个品牌</em>。"',
 mk_p:'在 BNI 互相引荐时，我常看到介绍在对方问"这位代表具体做什么？"时中断，因为没有可以展示的地方。BizHome 就是回答这个问题的官网。',
 mk_who:'宋承勋 · T.M Link 代表 · BNI Pioneer（釜山）',
 f_h:'下一次介绍，用您的官网网址。',f_p:'釜山 · 全国远程制作 · 申请后 1 个工作日内联系',f_btn1:'申请 BizHome',f_btn2:'查看案例',
 ft_by:'宋承勋 · T.M Link · BNI Pioneer'
},
ja:{
 u1v:'無料',
 n5:'独自ドメイン連携は別途お問い合わせ',
 beta:'試験運用',
 p2_6:'🌏 最大 6 言語 + お客様の声セクション',
 p2_5:'🛠 1 年間の画像・デザイン修正込み（画像差し替え 2 回 + デザインリニューアル 1 回・11.5 万ウォン相当）',
 p2_4:'📊 月間訪問レポート — 何人が見て何を押したか',
 p2_3:'📩 問い合わせフォーム + 即時通知 — BizHome が営業ツールに',
 p2_2:'📣 マイお知らせボード — 商品・事例・お知らせをスマホからすぐ投稿',
 p2_1:'🎬 ヒーロー AI 動画 — 開いた瞬間から動くトップ画面',
 p2_0:'スタンダードの全内容 +',
 p1_12:'制作期間 約 3 日',
 p1_11:'無料ホスティング（維持費 0 円）',
 p1_10:'写真・デザインの変更は TM LINK が担当',
 p1_9:'✏️ いつでもすぐ直せる文章修正 — 依頼して待つ必要なし、修正ボタン一つで。英・日・中は自動翻訳',
 p1_8:'訪問・クリック統計（「カード状況」）',
 p1_7:'連絡先保存・共有・カードブック保存・MANDU 連携・QR',
 p1_6:'4 言語（韓・英・日・中）',
 p1_5:'ポートフォリオ（業種に必要な場合）',
 p1_4:'「こんな方を紹介してください」リファーラルセクション',
 p1_3:'紹介・Why・違い・経歴・サービスのセクション',
 p1_2:'AI 画像 2 枚 — ヒーロー画像 + プロフィール写真',
 p1_1:'1:1 オーダーメイドデザイン（テンプレートなし）',
 hint:'マウスホイールで自分でスクロール',
 sc3_p:'企画・デザイン・開発・管理まで。代表一人を紹介するには時間も費用も大きすぎます。',
 sc3_h:'会社のホームページ',
 sc3_w:'重すぎる',
 sc2_p:'紹介・経歴・サービス・リファーラルを一ページに。リンク一つで渡せて、約 3 日で完成。',
 sc2_h:'BizHome',
 sc2_w:'ちょうどいい',
 sc1_p:'名前と連絡先まで。何が得意か、なぜこの人なのかは伝えにくい。',
 sc1_h:'名刺一枚',
 sc1_w:'軽すぎる',
 live:'実際の BizHome サンプル · ソン・スンフン',
 cmp_src:'※ 相場の出典：<a href="https://kmong.com/best-gig/47--%EB%88%84%EA%B5%AC%EB%82%98-%EC%89%BD%EA%B2%8C-%EA%B0%9C%EC%9D%B8-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%A0%9C%EC%9E%91%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95" target="_blank" rel="noopener">Kmong「個人ホームページ制作」</a>見積データ（最低 40万 · 最高 180万 · 平均 80万ウォン、2026年10月確認）。機能・ページ数により異なります。',
 fh1:'1:1 企画・デザイン',fh2:'4 言語標準',fh3:'維持費 0 円',fh4:'約 3 日で完成',
 r6c:'カカオトークプレビュー · QR 標準',
 r6a:'モバイル・カカオトーク最適化は別作業',
 r6:'共有',
 c_web:'一般的な外注の個人ホームページ',
 cat5:'AI 四柱推命',
 cat4:'翻訳メッセンジャー',
 cat3:'名刺管理',
 cat2:'デジタル名刺',
 cat1:'パーソナルブランドサイト',
 nav_apps:'アプリ',nav_why:'BizHome',nav_price:'料金',nav_process:'制作の流れ',nav_cta:'申し込む',
 hero_tag:'名刺とホームページの間 · BizHome',
 hero_h:'名刺では足りず、<br/>ホームページは重すぎる時。<br/><span class="hl">BizHome。</span>',
 hero_sub:'名刺一枚には収まらない話を、ホームページほど重くなく。<b>BizHome</b> は紹介・経歴・サービス・リファーラルを一ページにまとめたパーソナルブランドサイトです。渡すのはリンク一つ、受け取った人はあなたをきちんと知ることができます。',
 hero_btn1:'BizHome の料金を見る',hero_btn2:'制作事例を見る',
 st1:'毎月の<br/>ホスティング費',st2:'標準対応<br/>言語',st3:'制作期間<br/>（スタンダード）',st4:'申込後の返信<br/>営業日以内',
 apps_h:'TM LINK のサービス',apps_sub:'代表サービスの BizHome と、必要に応じて別に使えるアプリ。すべて TM LINK が開発・運営しています。',
 app_badge:'代表サービス',app1_n:'BizHome',app1_d:'名刺より深く、ホームページより軽いパーソナルブランドサイト。代表一人のために 1:1 で企画・デザイン。',app1_t:'15万 · 25万ウォン →',
 app2_n:'オート名刺',app2_d:'名刺写真 1 枚、5 分で完成するデジタル名刺。6 種のテンプレートからすぐ発行。',app2_t:'5,900ウォンから →',
 app3_n:'カードブック',app3_d:'受け取った名刺を一か所に集め、覚えている断片だけですぐ探せる名刺帳。',app3_t:'無料で使う →',
 app4_n:'MANDU',app4_d:'言葉が違っても会話は一つに。14 言語をリアルタイム自動翻訳するメッセンジャー。',app4_t:'体験する →',
 app5_n:'JUJUDOSA',app5_d:'命式を読み、今の時期に合ったアドバイスを届ける AI 四柱推命相談。今日の運勢・相性も。',app5_t:'相談を始める →',
 why_h:'名刺より深く、<br/>ホームページより軽く。',
 why_sub:'渡すのは名刺のように簡単に、見せるのはホームページのように十分に。紹介された人が検索した時にちょうど必要な分だけ。',
 b1_h:'テンプレートではなく 1:1',b1_p:'業種・スタイル・顧客層を伺い代表が直接デザイン。同じ BizHome は二つとありません。',
 b2_h:'リンク一つで紹介完了',b2_p:'カカオトークのプレビューに写真と紹介がすぐ表示。QR コードもお渡しします。',
 b3_h:'「こんな方を紹介してください」',b3_p:'BNI のリファーラル構造をそのまま反映したパートナー・推薦セクション。',
 b4_h:'4 言語を標準搭載',b4_p:'韓・英・中・日の切替ボタン付き。海外バイヤーや外国人顧客にもそのまま送れます。',
 b5_h:'維持費 0 円',b5_p:'サーバー・ホスティング費用なしで運営を続けられます。公開後の月額管理費はありません。',
 b6_h:'文章はいつでもすぐ',b6_p:'連絡先・肩書・紹介文は、依頼して待つ必要なく修正ボタン一つですぐ変わります。英・日・中は自動翻訳、写真・デザインは TM LINK が担当。',
 cmp_h:'ホームページで依頼したらいくら？',cmp_sub:'同じ内容を外注プラットフォームで個人ホームページとして依頼する場合と比べました。',
 c_biz:'BizHome',
 
 r2:'価格',r2a:'<b class="mkt">平均 80万ウォン</b><span class="range">40万 〜 180万ウォン</span>',r2c:'<b class="our">15万 · 25万ウォン</b><span class="range">定額制 · プラン別の内容を公開</span>',
 r3:'進め方',r3a:'企画 → デザイン → 開発を段階的に',r3c:'1:1 相談後 約 3 日で完成',
 r4:'維持費',r4a:'ホスティング・ドメイン・管理費が別途',r4c:'ホスティング 0 円',
 r5:'多言語',r5a:'言語ごとに追加作業',r5c:'4 言語標準搭載',
 pr_h:'BizHome オーダーメイド、選ぶのは 2 つだけ。',pr_sub:'どちらもテンプレートなしの 1:1 制作。違いは「紹介で止まるか、営業まで進むか」。',
 p1_d:'あなたと仕事をきちんと紹介する BizHome',
 p1_btn:'スタンダードを申し込む',
 p2_best:'紹介を超えて営業まで',p2_d:'見せて、知らせて、問い合わせまで受ける BizHome',
 p2_btn:'プレミアムを申し込む',
 n1:'消費税（VAT 10%）別',n2:'入金確認後に制作開始',n4:'10 枚以上の団体・企業は別途お見積り',
 g_h:'実際に制作した BizHome をご覧ください',g_p:'業種別の制作事例ギャラリーへ移動します',g_btn:'ギャラリーを見る',
 ps_h:'申し込みから完成まで 4 ステップ',ps_sub:'申込書は 1 分で完了。残りは会話しながら一緒に作ります。',
 s1_h:'申込書の記入',s1_p:'プランを選び基本情報を残すだけ。1 営業日以内にご連絡します。',
 s2_h:'相談・資料のお渡し',s2_p:'お仕事・顧客・紹介してほしい方を伺い、写真やロゴを受け取ります。',
 s3_h:'デザイン・修正',s3_p:'オーダーメイドの初稿をお送りし、プランの修正回数内で仕上げます。',
 s4_h:'公開・QR のお渡し',s4_p:'ホームページのアドレスと QR をお渡し。今日からアドレス一つで自己紹介。',
 ac_h:'作り直さず、安くアップデート。',ac_sub:'BizHome のお客様専用アップデート料金です。',
 u1:'文章修正',u1d:'修正ボタンですぐ（月 1 回）',u2:'写真・画像の差し替え',u2d:'プロフィール・カバーなど',u3:'デザインリニューアル',u3v:'50% オフ',u3d:'構成・レイアウト変更',u4:'全面作り直し',u4v:'30% オフ',u4d:'業種・ブランド転換',
 rf1:'制作開始前',rf1v:'100% 返金',rf2:'1 回目の修正前',rf2v:'50% 返金',rf3:'1 回目の修正後',rf3v:'返金不可',
 mk_q:'「代表一人が<em>一つのブランド</em>になるように作ります。」',
 mk_p:'BNI で紹介をやり取りする中で、「この代表は具体的に何をしている方？」と聞かれた時に見せる場所がなく、紹介が止まる場面をよく見ました。BizHome はその問いに答えるホームページです。',
 mk_who:'ソン・スンフン · T.M Link 代表 · BNI Pioneer（釜山）',
 f_h:'次の紹介は、あなたのホームページのアドレスで。',f_p:'釜山 · 全国リモート制作 · 申込後 1 営業日以内にご連絡',f_btn1:'BizHome を申し込む',f_btn2:'制作事例を見る',
 ft_by:'ソン・スンフン · T.M Link · BNI Pioneer'
}};


// 홈·앱 소개 페이지에서 새로 쓰는 문구
(function(){
  var add = {
    en:{ nav_about:'About', nav_home:'← TM LINK Home', ap_back:'← All services',
         h_tag:'TM LINK · Apps that connect people', h_h:'We build apps<br/>that connect people.',
         h_sub:'TM LINK builds and runs its own apps: digital business cards, a card book, a translation messenger, AI fortune counseling — and BizHome, a personal brand homepage made for one person.',
         h_btn1:'Explore services', h_btn2:'See BizHome', hf_h:'Let’s build yours.', hf_p:'Busan · Remote nationwide · We reply within 1 business day', hf_btn:'Apply for BizHome' },
    zh:{ nav_about:'关于', nav_home:'← TM LINK 首页', ap_back:'← 全部服务',
         h_tag:'TM LINK · 连接人与人的应用', h_h:'我们制作<br/>连接人与人的应用。',
         h_sub:'TM LINK 亲自开发并运营：数字名片、名片册、翻译聊天工具、AI 命理咨询，以及为一个人量身打造的个人品牌主页 BizHome。',
         h_btn1:'查看服务', h_btn2:'了解 BizHome', hf_h:'一起打造您的品牌。', hf_p:'釜山 · 全国远程制作 · 1 个工作日内回复', hf_btn:'申请 BizHome' },
    ja:{ nav_about:'紹介', nav_home:'← TM LINK ホーム', ap_back:'← サービス一覧',
         h_tag:'TM LINK · 人と人をつなぐアプリ', h_h:'人と人をつなぐ<br/>アプリを作っています。',
         h_sub:'TM LINK はデジタル名刺、名刺帳、通訳メッセンジャー、AI 占い相談、そして代表お一人のための個人ブランドホームページ BizHome を自社で開発・運営しています。',
         h_btn1:'サービスを見る', h_btn2:'BizHome を見る', hf_h:'あなたのブランドを一緒に。', hf_p:'釜山 · 全国リモート制作 · 1 営業日以内にご連絡', hf_btn:'BizHome を申し込む' }
  };
  Object.keys(add).forEach(function(l){ Object.assign(I18N[l], add[l]); });
})();

// 앱 소개 페이지: <main id="appPage" data-app="mandu"> 안의 내용을 현재 언어로 다시 그린다
function renderAppPage(){
  var root = document.getElementById('appPage'); if (!root) return;
  var $ = function(id){ return document.getElementById(id); };
  var a = APPS[root.dataset.app], d = a[curLang] || a.ko, u = SHEET_UI[curLang] || SHEET_UI.ko;
  function list(el, arr){ el.innerHTML=''; arr.forEach(function(t){ var li=document.createElement('li'); li.textContent=t; el.appendChild(li); }); }
  $('apCat').textContent = d.cat;
  $('apTitle').innerHTML = ''; $('apTitle').appendChild(document.createTextNode(d.name));
  if (d.name !== a.latin) { var sm=document.createElement('small'); sm.textContent=a.latin; $('apTitle').appendChild(sm); }
  $('apLead').textContent = d.lead;
  $('apWhenH').textContent = u.when; list($('apWhen'), d.when);
  $('apFeatH').textContent = u.feat; list($('apFeat'), d.feat);
  $('apPriceH').textContent = u.price; $('apPrice').textContent = d.price;
  $('apOpenT').textContent = d.open; $('apInstallBtn').textContent = u.install;
  $('apNote').textContent = u.note; list($('apIos'), u.ios); list($('apAnd'), u.and);
  document.title = d.name + (d.name !== a.latin ? ' ' + a.latin : '') + ' | TM LINK';
}
(function(){
  var root = document.getElementById('appPage'); if (!root) return;
  var $ = function(id){ return document.getElementById(id); };
  var ua = navigator.userAgent, os = /iPhone|iPad|iPod/.test(ua) || (/Macintosh/.test(ua) && navigator.maxTouchPoints > 1) ? 'ios' : /Android/.test(ua) ? 'android' : '';
  document.querySelectorAll('.si-os').forEach(function(el){ el.hidden = !!os && el.dataset.os !== os; });
  $('apInstallBtn').addEventListener('click', function(){
    var box = $('apInstall'), open = box.hidden; box.hidden = !open; this.setAttribute('aria-expanded', open ? 'true' : 'false');
  });
  window.renderSheet = renderAppPage;
})();

function setLang(lang){
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    if(el.dataset.ko === undefined) el.dataset.ko = el.innerHTML;   // 한국어 원문 보관
    var d = I18N[lang];
    el.innerHTML = (lang === 'ko' || !d || d[el.dataset.i18n] === undefined) ? el.dataset.ko : d[el.dataset.i18n];
  });
  document.documentElement.lang = lang;
  curLang = lang; if (window.renderSheet) renderSheet();
  document.querySelectorAll('.lang button').forEach(function(b){
    b.setAttribute('aria-pressed', b.dataset.lang === lang ? 'true' : 'false');
  });
  try{ localStorage.setItem('tmlink-lang', lang); }catch(e){}
}
document.querySelectorAll('.lang button').forEach(function(b){
  b.addEventListener('click', function(){ setLang(b.dataset.lang); });
});
try{ var saved = localStorage.getItem('tmlink-lang'); if(saved && saved !== 'ko') setLang(saved); }catch(e){}
